version: 0.0
os: linux 

files:
    - source: / 
      destination: /home/ubuntu/node-express-realworld-example-app
      timeout: 300
     
      


hooks:
   
   
   BeforeInstall:
         - location: /script/stop_server.sh
           timeout: 300
           runas: root
      
   ApplicationStart:
         - location: /script/start_server.sh
           timeout: 300
           runas: root
