version: 0.2

env: 
   
   parameter-store:
                Mongo_Url: "/vaibhav/mongo_url"

phases:
   build:
       commands:
           - sed -i "s/localhost/"$Mongo_Url"/" app.js  



artifacts:
        files: 
            - " **/* "
